<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260507143921 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE absences (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id_id INT NOT NULL, proof_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F9C0EFFF9D86650F ON absences (user_id_id)');
        $this->addSql('CREATE INDEX IDX_F9C0EFFFD7086615 ON absences (proof_id)');
        $this->addSql('CREATE TABLE class_documents (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, visibility BOOLEAN NOT NULL, class_id_id INT NOT NULL, document_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C96FEDB79993BF61 ON class_documents (class_id_id)');
        $this->addSql('CREATE INDEX IDX_C96FEDB716E5E825 ON class_documents (document_id_id)');
        $this->addSql('CREATE TABLE class_users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id_id INT NOT NULL, class_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F25484DF9D86650F ON class_users (user_id_id)');
        $this->addSql('CREATE INDEX IDX_F25484DF9993BF61 ON class_users (class_id_id)');
        $this->addSql('CREATE TABLE classes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, professor_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2ED7EC5F73333AC ON classes (professor_id_id)');
        $this->addSql('CREATE TABLE documents (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) DEFAULT NULL, title VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A2B072889D86650F ON documents (user_id_id)');
        $this->addSql('CREATE TABLE grades (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, grade VARCHAR(20) NOT NULL, comments TEXT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, class_id_id INT NOT NULL, student_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3AE361109993BF61 ON grades (class_id_id)');
        $this->addSql('CREATE INDEX IDX_3AE36110F773E7CA ON grades (student_id_id)');
        $this->addSql('CREATE TABLE homework (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, class_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8C600B4E9993BF61 ON homework (class_id_id)');
        $this->addSql('CREATE TABLE notification_recipients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_read BOOLEAN NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notification_id_id INT NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF1497E6B9F07BAE ON notification_recipients (notification_id_id)');
        $this->addSql('CREATE INDEX IDX_EF1497E69D86650F ON notification_recipients (user_id_id)');
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, type TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE schedules (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week VARCHAR(255) NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, room VARCHAR(255) NOT NULL, class_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_313BDC8E9993BF61 ON schedules (class_id_id)');
        $this->addSql('CREATE TABLE textbooks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, class_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_104024BC9993BF61 ON textbooks (class_id_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, role TEXT NOT NULL, phone_number VARCHAR(20) NOT NULL, parent_phone_number VARCHAR(20) NOT NULL, parent_email VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE user_actions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ip VARCHAR(20) DEFAULT NULL, action TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5D45EFE59D86650F ON user_actions (user_id_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE absences ADD CONSTRAINT FK_F9C0EFFF9D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE absences ADD CONSTRAINT FK_F9C0EFFFD7086615 FOREIGN KEY (proof_id) REFERENCES documents (id)');
        $this->addSql('ALTER TABLE class_documents ADD CONSTRAINT FK_C96FEDB79993BF61 FOREIGN KEY (class_id_id) REFERENCES classes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE class_documents ADD CONSTRAINT FK_C96FEDB716E5E825 FOREIGN KEY (document_id_id) REFERENCES documents (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE class_users ADD CONSTRAINT FK_F25484DF9D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE class_users ADD CONSTRAINT FK_F25484DF9993BF61 FOREIGN KEY (class_id_id) REFERENCES classes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE classes ADD CONSTRAINT FK_2ED7EC5F73333AC FOREIGN KEY (professor_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE documents ADD CONSTRAINT FK_A2B072889D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE grades ADD CONSTRAINT FK_3AE361109993BF61 FOREIGN KEY (class_id_id) REFERENCES classes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE grades ADD CONSTRAINT FK_3AE36110F773E7CA FOREIGN KEY (student_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE homework ADD CONSTRAINT FK_8C600B4E9993BF61 FOREIGN KEY (class_id_id) REFERENCES classes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification_recipients ADD CONSTRAINT FK_EF1497E6B9F07BAE FOREIGN KEY (notification_id_id) REFERENCES notifications (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification_recipients ADD CONSTRAINT FK_EF1497E69D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedules ADD CONSTRAINT FK_313BDC8E9993BF61 FOREIGN KEY (class_id_id) REFERENCES classes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE textbooks ADD CONSTRAINT FK_104024BC9993BF61 FOREIGN KEY (class_id_id) REFERENCES classes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_actions ADD CONSTRAINT FK_5D45EFE59D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE absences DROP CONSTRAINT FK_F9C0EFFF9D86650F');
        $this->addSql('ALTER TABLE absences DROP CONSTRAINT FK_F9C0EFFFD7086615');
        $this->addSql('ALTER TABLE class_documents DROP CONSTRAINT FK_C96FEDB79993BF61');
        $this->addSql('ALTER TABLE class_documents DROP CONSTRAINT FK_C96FEDB716E5E825');
        $this->addSql('ALTER TABLE class_users DROP CONSTRAINT FK_F25484DF9D86650F');
        $this->addSql('ALTER TABLE class_users DROP CONSTRAINT FK_F25484DF9993BF61');
        $this->addSql('ALTER TABLE classes DROP CONSTRAINT FK_2ED7EC5F73333AC');
        $this->addSql('ALTER TABLE documents DROP CONSTRAINT FK_A2B072889D86650F');
        $this->addSql('ALTER TABLE grades DROP CONSTRAINT FK_3AE361109993BF61');
        $this->addSql('ALTER TABLE grades DROP CONSTRAINT FK_3AE36110F773E7CA');
        $this->addSql('ALTER TABLE homework DROP CONSTRAINT FK_8C600B4E9993BF61');
        $this->addSql('ALTER TABLE notification_recipients DROP CONSTRAINT FK_EF1497E6B9F07BAE');
        $this->addSql('ALTER TABLE notification_recipients DROP CONSTRAINT FK_EF1497E69D86650F');
        $this->addSql('ALTER TABLE schedules DROP CONSTRAINT FK_313BDC8E9993BF61');
        $this->addSql('ALTER TABLE textbooks DROP CONSTRAINT FK_104024BC9993BF61');
        $this->addSql('ALTER TABLE user_actions DROP CONSTRAINT FK_5D45EFE59D86650F');
        $this->addSql('DROP TABLE absences');
        $this->addSql('DROP TABLE class_documents');
        $this->addSql('DROP TABLE class_users');
        $this->addSql('DROP TABLE classes');
        $this->addSql('DROP TABLE documents');
        $this->addSql('DROP TABLE grades');
        $this->addSql('DROP TABLE homework');
        $this->addSql('DROP TABLE notification_recipients');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE schedules');
        $this->addSql('DROP TABLE textbooks');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_actions');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
