<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260602093335 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attendance_signature (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, comment TEXT DEFAULT NULL, signed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT NOT NULL, promotion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB0CAB7BCB944F1A ON attendance_signature (student_id)');
        $this->addSql('CREATE INDEX IDX_DB0CAB7B139DF194 ON attendance_signature (promotion_id)');
        $this->addSql('ALTER TABLE attendance_signature ADD CONSTRAINT FK_DB0CAB7BCB944F1A FOREIGN KEY (student_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attendance_signature ADD CONSTRAINT FK_DB0CAB7B139DF194 FOREIGN KEY (promotion_id) REFERENCES promotions (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attendance_signature DROP CONSTRAINT FK_DB0CAB7BCB944F1A');
        $this->addSql('ALTER TABLE attendance_signature DROP CONSTRAINT FK_DB0CAB7B139DF194');
        $this->addSql('DROP TABLE attendance_signature');
    }
}
