<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260512133254 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE absences (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id_id INT NOT NULL, document_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F9C0EFFF9D86650F ON absences (user_id_id)');
        $this->addSql('CREATE INDEX IDX_F9C0EFFF16E5E825 ON absences (document_id_id)');
        $this->addSql('CREATE TABLE documents (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A2B072889D86650F ON documents (user_id_id)');
        $this->addSql('CREATE TABLE grades (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, grade VARCHAR(255) DEFAULT NULL, comments TEXT DEFAULT NULL, submission VARCHAR(255) DEFAULT NULL, update_history TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id_id INT NOT NULL, student_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3AE361106C1197C9 ON grades (project_id_id)');
        $this->addSql('CREATE INDEX IDX_3AE36110F773E7CA ON grades (student_id_id)');
        $this->addSql('CREATE TABLE notification_recipients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_read BOOLEAN NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notification_id_id INT NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF1497E6B9F07BAE ON notification_recipients (notification_id_id)');
        $this->addSql('CREATE INDEX IDX_EF1497E69D86650F ON notification_recipients (user_id_id)');
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, message TEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE projects (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, visibility BOOLEAN NOT NULL, description TEXT NOT NULL, google_drive VARCHAR(255) DEFAULT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, prmotion_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5C93B3A4D33488F ON projects (prmotion_id_id)');
        $this->addSql('CREATE TABLE promotions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, professor_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EA1B3034F73333AC ON promotions (professor_id_id)');
        $this->addSql('CREATE TABLE promtion_users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id_id INT NOT NULL, promotion_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D2A3546F9D86650F ON promtion_users (user_id_id)');
        $this->addSql('CREATE INDEX IDX_D2A3546F1F42EA0A ON promtion_users (promotion_id_id)');
        $this->addSql('CREATE TABLE user_actions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5D45EFE59D86650F ON user_actions (user_id_id)');
        $this->addSql('ALTER TABLE absences ADD CONSTRAINT FK_F9C0EFFF9D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE absences ADD CONSTRAINT FK_F9C0EFFF16E5E825 FOREIGN KEY (document_id_id) REFERENCES documents (id)');
        $this->addSql('ALTER TABLE documents ADD CONSTRAINT FK_A2B072889D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE grades ADD CONSTRAINT FK_3AE361106C1197C9 FOREIGN KEY (project_id_id) REFERENCES projects (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE grades ADD CONSTRAINT FK_3AE36110F773E7CA FOREIGN KEY (student_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification_recipients ADD CONSTRAINT FK_EF1497E6B9F07BAE FOREIGN KEY (notification_id_id) REFERENCES notifications (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification_recipients ADD CONSTRAINT FK_EF1497E69D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A4D33488F FOREIGN KEY (prmotion_id_id) REFERENCES promotions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE promotions ADD CONSTRAINT FK_EA1B3034F73333AC FOREIGN KEY (professor_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE promtion_users ADD CONSTRAINT FK_D2A3546F9D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE promtion_users ADD CONSTRAINT FK_D2A3546F1F42EA0A FOREIGN KEY (promotion_id_id) REFERENCES promotions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_actions ADD CONSTRAINT FK_5D45EFE59D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE absences DROP CONSTRAINT FK_F9C0EFFF9D86650F');
        $this->addSql('ALTER TABLE absences DROP CONSTRAINT FK_F9C0EFFF16E5E825');
        $this->addSql('ALTER TABLE documents DROP CONSTRAINT FK_A2B072889D86650F');
        $this->addSql('ALTER TABLE grades DROP CONSTRAINT FK_3AE361106C1197C9');
        $this->addSql('ALTER TABLE grades DROP CONSTRAINT FK_3AE36110F773E7CA');
        $this->addSql('ALTER TABLE notification_recipients DROP CONSTRAINT FK_EF1497E6B9F07BAE');
        $this->addSql('ALTER TABLE notification_recipients DROP CONSTRAINT FK_EF1497E69D86650F');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A4D33488F');
        $this->addSql('ALTER TABLE promotions DROP CONSTRAINT FK_EA1B3034F73333AC');
        $this->addSql('ALTER TABLE promtion_users DROP CONSTRAINT FK_D2A3546F9D86650F');
        $this->addSql('ALTER TABLE promtion_users DROP CONSTRAINT FK_D2A3546F1F42EA0A');
        $this->addSql('ALTER TABLE user_actions DROP CONSTRAINT FK_5D45EFE59D86650F');
        $this->addSql('DROP TABLE absences');
        $this->addSql('DROP TABLE documents');
        $this->addSql('DROP TABLE grades');
        $this->addSql('DROP TABLE notification_recipients');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE projects');
        $this->addSql('DROP TABLE promotions');
        $this->addSql('DROP TABLE promtion_users');
        $this->addSql('DROP TABLE user_actions');
    }
}
