<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260513072820 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE promotion_users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, promotion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7485D1B4A76ED395 ON promotion_users (user_id)');
        $this->addSql('CREATE INDEX IDX_7485D1B4139DF194 ON promotion_users (promotion_id)');
        $this->addSql('ALTER TABLE promotion_users ADD CONSTRAINT FK_7485D1B4A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE promotion_users ADD CONSTRAINT FK_7485D1B4139DF194 FOREIGN KEY (promotion_id) REFERENCES promotions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE promtion_users DROP CONSTRAINT fk_d2a3546fa76ed395');
        $this->addSql('ALTER TABLE promtion_users DROP CONSTRAINT fk_d2a3546f139df194');
        $this->addSql('DROP TABLE promtion_users');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE promtion_users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, promotion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_d2a3546fa76ed395 ON promtion_users (user_id)');
        $this->addSql('CREATE INDEX idx_d2a3546f139df194 ON promtion_users (promotion_id)');
        $this->addSql('ALTER TABLE promtion_users ADD CONSTRAINT fk_d2a3546fa76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promtion_users ADD CONSTRAINT fk_d2a3546f139df194 FOREIGN KEY (promotion_id) REFERENCES promotions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promotion_users DROP CONSTRAINT FK_7485D1B4A76ED395');
        $this->addSql('ALTER TABLE promotion_users DROP CONSTRAINT FK_7485D1B4139DF194');
        $this->addSql('DROP TABLE promotion_users');
    }
}
