<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260602070607 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE presence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, signed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6977C7A5CB944F1A ON presence (student_id)');
        $this->addSql('ALTER TABLE presence ADD CONSTRAINT FK_6977C7A5CB944F1A FOREIGN KEY (student_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attendance ADD signed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE notifications ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE notifications ADD sender_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3F624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_6000B0D3F624B39D ON notifications (sender_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE presence DROP CONSTRAINT FK_6977C7A5CB944F1A');
        $this->addSql('DROP TABLE presence');
        $this->addSql('ALTER TABLE attendance DROP signed_at');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3F624B39D');
        $this->addSql('DROP INDEX IDX_6000B0D3F624B39D');
        $this->addSql('ALTER TABLE notifications DROP created_at');
        $this->addSql('ALTER TABLE notifications DROP sender_id');
    }
}
