<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260604090015 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attendance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, comment TEXT DEFAULT NULL, signed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, student_id INT NOT NULL, promotion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6DE30D91CB944F1A ON attendance (student_id)');
        $this->addSql('CREATE INDEX IDX_6DE30D91139DF194 ON attendance (promotion_id)');
        $this->addSql('CREATE TABLE attendance_signature (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, comment TEXT DEFAULT NULL, signed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT NOT NULL, promotion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB0CAB7BCB944F1A ON attendance_signature (student_id)');
        $this->addSql('CREATE INDEX IDX_DB0CAB7B139DF194 ON attendance_signature (promotion_id)');
        $this->addSql('CREATE TABLE presence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, signed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6977C7A5CB944F1A ON presence (student_id)');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT FK_6DE30D91CB944F1A FOREIGN KEY (student_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT FK_6DE30D91139DF194 FOREIGN KEY (promotion_id) REFERENCES promotions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attendance_signature ADD CONSTRAINT FK_DB0CAB7BCB944F1A FOREIGN KEY (student_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attendance_signature ADD CONSTRAINT FK_DB0CAB7B139DF194 FOREIGN KEY (promotion_id) REFERENCES promotions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE presence ADD CONSTRAINT FK_6977C7A5CB944F1A FOREIGN KEY (student_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE grades ADD promotion_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE grades ADD CONSTRAINT FK_3AE36110139DF194 FOREIGN KEY (promotion_id) REFERENCES promotions (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_3AE36110139DF194 ON grades (promotion_id)');
        $this->addSql('ALTER TABLE notifications ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW() NOT NULL');
        $this->addSql('ALTER TABLE notifications ADD sender_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3F624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_6000B0D3F624B39D ON notifications (sender_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT FK_6DE30D91CB944F1A');
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT FK_6DE30D91139DF194');
        $this->addSql('ALTER TABLE attendance_signature DROP CONSTRAINT FK_DB0CAB7BCB944F1A');
        $this->addSql('ALTER TABLE attendance_signature DROP CONSTRAINT FK_DB0CAB7B139DF194');
        $this->addSql('ALTER TABLE presence DROP CONSTRAINT FK_6977C7A5CB944F1A');
        $this->addSql('DROP TABLE attendance');
        $this->addSql('DROP TABLE attendance_signature');
        $this->addSql('DROP TABLE presence');
        $this->addSql('ALTER TABLE grades DROP CONSTRAINT FK_3AE36110139DF194');
        $this->addSql('DROP INDEX IDX_3AE36110139DF194');
        $this->addSql('ALTER TABLE grades DROP promotion_id');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3F624B39D');
        $this->addSql('DROP INDEX IDX_6000B0D3F624B39D');
        $this->addSql('ALTER TABLE notifications DROP created_at');
        $this->addSql('ALTER TABLE notifications DROP sender_id');
    }
}
